### ISSUE TITLE
Azure OpenAI integration

### ISSUE THREAD

**Issue by itsPreto** [danswer-ai/danswer#165]
From what I can tell all this tool does is pull relevant chunks of text from, _more often than not_, proprietary data and sends it to openai's completion api to get a coherent reply-- 

- IMO it needs to integrate something like Azure OpenAI which lets you host your own version of their models in a cloud environment, so you essentially get your own private server which all the requests will be routed to.
- either that or like others have pointed out, you allow for either locally hosted models or custom apis.

**Comment by yuhongsun96** [comment]
The first part of locally hosted models and custom apis are mentioned in https://github.com/danswer-ai/danswer/issues/116.

The Azure OpenAI integration is also valid though so we will consider that as well. It's somewhat less urgent though based on the feedback. Seems 95% of people asking for something in this realm want opensource/private models.

I'm fairly sure Azure OpenAI is also an API call since it seems fairly infeasible to decide to self host a model like GPT-4 on 8 a100 GPUs... it's very expensive.

Also both OpenAI and Azure have a 30 day retention of the user input + model output and both are SOC2 certified so not too clear what the difference is.

Could you please clarify why Azure OpenAI is considered more secure?

**Comment by hacksider** [comment]
Reason why openai is more secure is that it have Enterprise-grade security with role-based access control (RBAC) and private networks

**Comment by chrisedington** [comment]
I'm also a fan of using Azure OpenAI for usage on private data, networking & security and fine-training capabilities.

**Comment by yuhongsun96** [comment]
Renaming this one to Azure OpenAI integration, this seems to be the ask here.
Also since local/self hosted models is already covered by https://github.com/danswer-ai/danswer/issues/116

**Comment by 415matt** [comment]
To the question of OpenAI vs Azure: Most enterprises already have existing agreements & services with Microsoft - (O365, Active Directory, Exchange) and feel much more comfortable sending data to them, regardless of how minimal the difference in retention/data privacy may be in reality.

I'll start working on this issue, however it may take some time to verify my code works - right now Azure OpenAI is by request only and it will take some time for other teams in my org to submit the request and deploy the endpoint.

**Comment by 415matt** [comment]
If anyone currently has OpenAI Azure Service access, feel free to test out my code:
https://github.com/415matt/danswer

**Necessary env variables:**
ENABLE_OPENAI_AZURE = "true"
AZURE_API_BASE = "https://example-endpoint.openai.azure.com"
AZURE_DEPLOYMENT_ID = "your-deployment-id"

**Comment by xuanyue202** [comment]
@415matt there is NO changes found in your fork. did you push the branch you are working on ?

**Comment by 415matt** [comment]
@xuanyue202 Sorry about that, check out #293

**Comment by yuhongsun96** [comment]
Hi all,

The code made it into main today, thanks @415matt for your contribution!

Docs for setting up Danswer + Azure OpenAI: https://docs.danswer.dev/gen_ai_configs/azure
Code Tag: v0.1.5
DockerHub: v0.1.5 (which is also latest for now)
