### ISSUE TITLE
答非所问？？为啥我用出来和演示的不一样

### ISSUE THREAD

**Issue by mozeqiu123** [danswer-ai/danswer#215]
![image](https://github.com/danswer-ai/danswer/assets/139750690/b2f0347d-4fd8-4ffd-a62a-980ce9fedd73)

**Comment by yuhongsun96** [comment]
We split documents into sections of a certain number of characters and then do some additional processing like including overlaps. English words are many characters per token, while as I believe Chinese characters are 1 character per token.

We don't translate characters to tokens because of the extra overhead.

You would need to change some parameters:
https://github.com/danswer-ai/danswer/blob/main/backend/danswer/configs/app_configs.py#L112
maybe make this one 500?

Also, the default models are English models, you may want to pick chinese or multilingual models here:
https://github.com/danswer-ai/danswer/blob/main/backend/danswer/configs/model_configs.py#L11

**Comment by yuhongsun96** [comment]
Settings are for english. You are using chinese. You need to change settings

**Comment by ws1hope** [comment]
> ![image](https://user-images.githubusercontent.com/139750690/254571373-b2f0347d-4fd8-4ffd-a62a-980ce9fedd73.png)

他这个项目对你输入的中文文件编码后就是乱码的，只支持英文的，要改一下编码方法才可以

**Comment by scriptboy1990** [comment]
> > ![image](https://user-images.githubusercontent.com/139750690/254571373-b2f0347d-4fd8-4ffd-a62a-980ce9fedd73.png)
> 
> 他这个项目对你输入的中文文件编码后就是乱码的，只支持英文的，要改一下编码方法才可以

怎么改呢，知道吗，想导入中文数据。
