### ISSUE TITLE
Preventing Cross Website Data in search results

### ISSUE THREAD

**Issue by bslavin** [danswer-ai/danswer#2152]
I am trying to index multiple support sites:

http://support.<your_domain>.com/support/sitemap.xml
http://support.<your_domain2>.com/support/sitemap.xml
(Freshdesk calls this portals) They are all from the same account but different contents. 

Each of these sites has different answers to similar questions. 

An example

- the location of the login portal
- how to pay bills etc
- Locations of status pages, billing details

I have them setup like this:

<img width="1272" alt="image" src="https://github.com/user-attachments/assets/2d6bd06e-1bda-4b20-b09a-f67af9e0c1a9">

However in the portal I can't specifically exclude or include a specific Web Portal from the responses. 

<img width="328" alt="image" src="https://github.com/user-attachments/assets/c424a16d-7efb-480b-97dc-585ae28002b9">

Ideally I would like the responses to only show data indexed from one portal or the other, not both. Is this the what `knowledge sets` are used for?

**Comment by tejaspatil0407** [comment]
Is this how you are accessing your freshdesk data? If so, how are you getting past the need of signing in? I have created a connector for freshdesk and is working decently, but if there is native support I would love to know how you did this!

**Comment by mydnic** [comment]
> Is this how you are accessing your freshdesk data? If so, how are you getting past the need of signing in? I have created a connector for freshdesk and is working decently, but if there is native support I would love to know how you did this!

@tejaspatil0407 does your connector fetch the content of the customer tickets ? Or only the "Knowledge base" stored in freshdesk ? 

In my case we use Freshdesk only for customer tickets and most of the time it's to answer questions about our products. I'm curious if and how we could import all those tickets into Danswer

**Comment by tejaspatil0407** [comment]
It collects all ticket data, but i am having a little problems as the entire ticket contents arent being read, so other than the initial ticket raised by the customer the responses/resolutions arent being stored. It refreshes every 5 minutes but another problem is that the data is in JSON and ive found that danswer finds it a bit difficult to understand json as multiple times ive had it return that no tickets are found for a certain ticket ID but using tags ive been able select and chat with the ticket.

I could give you the connector code but currently its a WIP and we have kept it on the side due to problems with regulations as the data that goes to ChatGPT gets stored and is not secure enough for us, and are moving to a localAI system but until then there wont be any changes to the freshdesk connector code.
