### ISSUE TITLE
any way to disable ai feedback in slack?

### ISSUE THREAD

**Issue by elvis-cai** [danswer-ai/danswer#2411]
Hi team
we found https://github.com/danswer-ai/danswer/blob/58bdf9d684ade052f219b4733b936924250cee9d/backend/danswer/danswerbot/slack/blocks.py#L388 block to decide enable or not, is there any config or env we could use to control it since by default it will have the helpful or not helpful button?
Thanks

**Comment by sahil-sharma-50** [comment]
Reopening this issue because it directly matches the requested Slack configuration option.

PR: https://github.com/onyx-dot-app/onyx/pull/14009

Proposed scope:

- Add a General Configuration checkbox for default and channel-specific Slack configurations: `Remove the 'Helpful' and 'Not helpful' buttons after bot response.`
- Store the setting as `remove_feedback_buttons` in the existing JSON channel configuration.
- Preserve current behavior by default for existing configurations.
- Hide only the Helpful and Not helpful controls when enabled.
- Skip scheduled feedback reminders when those controls are disabled.
- Preserve the setting through ephemeral response actions.
- Do not add a database migration or change Web UI feedback behavior.

The implementation includes backend and frontend regression tests. @yuhongsun96, please review the scope and design for approval.
