### ISSUE TITLE
.danswer_metadata.json is ignored in File connector

### ISSUE THREAD

**Issue by zsolt-dev** [danswer-ai/danswer#2555]
I am uploading a zip with 800 html files and a `.danswer_metadata.json`

`.danswer_metadata.json` format:

```
[
  {
    "filename": "something-interesting.html",
    "link": "https://example.com/something-interesting"
  },
  ...
 ```
 
 The results are not clickable and when hovering on the icon I can see this:
 
 
<img width="163" alt="image" src="https://github.com/user-attachments/assets/54cb1a56-18e3-4952-8c28-6a59a59397da">

In the admin panel, explorer menu I could see the `.danswer_metadata.json` being there.

**Comment by jefimserg** [comment]
I think the only way it works, is when you put all files along with .danswer_metadata.json in zip file and upload single zip.

**Comment by jefimserg** [comment]
Check the log file of the index container after zip upload, by default using docker it should look something like: docker logs danswer-stack-indexing_model_server-1
   
Based on code you should have in the logs one of these:
logger.warn(f"Unable to load {DANSWER_METADATA_FILENAME}")
or
logger.info(f"No {DANSWER_METADATA_FILENAME} file")

In first case it's a syntax error in .danswer_metadata.json in second case file was not captured. The fact that you have .danswer_metadata.json visible in explorer is also strange, because metadata file is not indexed. Could also be a case that someone has updated backend/danswer/configs/constants.py and changed DANSWER_METADATA_FILENAME, by default it must be:
DANSWER_METADATA_FILENAME = ".danswer_metadata.json"

**Comment by yuhongsun96** [comment]
It needs to be at the very base of the zip, sometime people create the zip from like a directory above so every file will be dir/file.txt instead of file.txt for example. The metadata file would be nested like that too and so it won't get picked up
