### ISSUE TITLE
Cannot configure API keys

### ISSUE THREAD

**Issue by ahmadassaf** [danswer-ai/danswer#3191]
The API keys page keep giving 404

<img width="800" alt="image" src="https://github.com/user-attachments/assets/5e0a402a-489f-4de2-b6ee-2fa27532bbad">

**Comment by MaximilianoAdaro** [comment]
Are there any updates on this? Have the same issue

**Comment by elvis-cai** [comment]
+1 0.14.0
<img width="725" alt="image" src="https://github.com/user-attachments/assets/d02d292b-3bc3-4d8e-986e-80320eb15916">

**Comment by Weves** [comment]
@ahmadassaf @elvis-cai @MaximilianoAdaro this has been fixed in the latest nightly release (by https://github.com/danswer-ai/danswer/commit/36941ae663a646d36d10bec8cc5825dd58c504fd + https://github.com/danswer-ai/danswer/commit/fd84b7a768455d6cc8fc0e8f4a9f6d6e63ab81a7)! It will be coming to the v0.15 beta next week as well.

Let me know if you run into any additional issues with this one.
