### ISSUE TITLE
Permit to Skip Documents with Less Than X Chunks/Document to be Sent to LLM

### ISSUE THREAD

**Issue by YoranSys** [danswer-ai/danswer#375]
Description:

Currently, when sources like Slack or chat are enabled, many irrelevant documents are sent to the Language Models (LLMs) like GPT-4, Llama2, Orca, etc. These documents often contain very few chunks of relevant information which could potentially affect the efficiency of the LLMs.
Expected Behavior:

The system should have a feature that allows us to set a minimum limit for the number of chunks a document should have before it is sent to the LLMs. If a document does not meet this minimum limit, it should be skipped and not sent to the LLMs.
Current Behavior:

The system currently sends all documents, regardless of their chunk size, to the LLMs. This can lead to the LLMs processing a large number of irrelevant documents, which could affect their efficiency and the quality of the results they produce.
Possible Solution:

Implement a feature that sets a minimum limit for the number of chunks a document should have before it is sent to the LLMs. This limit could be customizable based on the requirements of the user.
Steps to Reproduce:

    Enable sources like Slack or chat.
    Observe the documents being sent to the LLMs.
    Note that documents with very few chunks are also being sent to the LLMs.

Context:

This issue is important because it affects the efficiency of the LLMs and the quality of the results they produce. By skipping irrelevant documents with very few chunks, we can ensure that the LLMs only process relevant and quality data.

**Comment by Weves** [comment]
So we're planning on making so you can set a token limit, and we'll keep feeding in chunks to the LLM until we hit that token limit. This will hopefully mean we'll be able to get past the smaller docs, and get to the good ones. 

We're also planning on adding "personas" / "document sets". These will be defined by you once, and then you can select a given set to search over when performing a query. You could exclude Slack from a document set and then search over.

I'm not sure if it's a safe assumption to say that in general smaller docs are not relevant / useful to the LLM output, which is why I'd prefer to tackle this issue a different way. Of course, happy to discuss more / get your feedback on this proposal!

**Comment by jignnsd** [comment]
I agree @Weves that not necessarily a small document is irrelevant to the search, in my tests that is not a rule. I like the approach! Thanks @YoranSys as well!

**Comment by Weves** [comment]
FYI: the change mentioned above has been pushed (https://github.com/danswer-ai/danswer/pull/401)!

You can now set the `NUM_DOCUMENT_TOKENS_FED_TO_GENERATIVE_MODEL` env variable if you want to override the default (currently `512 * 5`, which approximates 5 full chunks).
