### ISSUE TITLE
Chat doesn't use indexed data in vespa when using Ollama (Llama 2)

### ISSUE THREAD

**Issue by arslan-autoscout24** [danswer-ai/danswer#881]
Using ollama as LLM I am not able to use indexed data in vespa.
I can see the document is indexed in Vespa by running the command

`vespa query 'yql=select * from sources * where true`

However asking a very simple question doesn't use this information. 

This seems like an issue using llama2 because it works using openapi.

**Comment by arslan70** [comment]
The issue was llama 2 was a bit overconfident and chose not to search. This PR will fix it
https://github.com/danswer-ai/danswer/pull/904

**Comment by yuhongsun96** [comment]
If it's a difference between models, then it's likely due to how different models react to the prompts. Looks like you've got it figured out?

We would love to hear from you about your use case and how Danswer has been performing for you! If you're open to it, we’d love to hear from you in our [Slack](https://join.slack.com/t/danswer/shared_invite/zt-1u3h3ke3b-VGh1idW19R8oiNRiKBYv2w) or [Discord](https://discord.gg/TDJ59cGV2X)! Alternatively if you want to have a quick chat with the maintainer (Chris and myself), you can just select a time on my [Cal](https://app.cal.com/yuhongsun)
